name: publish to nuget
on:
  push:
    branches:
      - Development # Default release branch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x' ]
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '12'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1

      # restore dependencies  
      - name: Install dependencies
        run: dotnet restore

      # Runs test
      - name: Run a multi-line script
        run: dotnet test       
     